//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat
    {
        public int cat_id { get; set; }
        public Nullable<int> catClass_id { get; set; }
        public Nullable<int> shop_id { get; set; }
        public Nullable<byte> cat_sex { get; set; }
        public Nullable<int> cat_price { get; set; }
        public Nullable<byte> isAntiepidemic { get; set; }
        public Nullable<byte> isInsect { get; set; }
        public Nullable<int> cat_num { get; set; }
        public Nullable<byte> isFullBlood { get; set; }
        public string cat_img { get; set; }
        public Nullable<byte> isRecommend { get; set; }
    
        public virtual catClass catClass { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
