//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.Cart = new HashSet<Cart>();
            this.goodComment = new HashSet<goodComment>();
        }
    
        public int good_id { get; set; }
        public int goodClass_id { get; set; }
        public string good_introduce { get; set; }
        public Nullable<int> good_price { get; set; }
        public string good_img { get; set; }
        public Nullable<System.DateTime> good_addtime { get; set; }
        public Nullable<int> orderDetails_id { get; set; }
        public Nullable<int> shop_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual goodClass goodClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<goodComment> goodComment { get; set; }
        public virtual orderDetails orderDetails { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
