//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakePrivate
    {
        public int myprivate_id { get; set; }
        public int Users_id { get; set; }
        public string destination { get; set; }
        public string customname { get; set; }
        public string phone { get; set; }
        public Nullable<decimal> expenses { get; set; }
        public Nullable<System.DateTime> dates { get; set; }
        public string tools { get; set; }
        public string notes { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
