//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CatpuziEntities : DbContext
    {
        public CatpuziEntities()
            : base("name=CatpuziEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Cat> Cat { get; set; }
        public virtual DbSet<catClass> catClass { get; set; }
        public virtual DbSet<goodClass> goodClass { get; set; }
        public virtual DbSet<goodComment> goodComment { get; set; }
        public virtual DbSet<goodReply> goodReply { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<info> info { get; set; }
        public virtual DbSet<infoClass> infoClass { get; set; }
        public virtual DbSet<infoComment> infoComment { get; set; }
        public virtual DbSet<infoReply> infoReply { get; set; }
        public virtual DbSet<MakePrivate> MakePrivate { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<orderDetails> orderDetails { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
