//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.Cart = new HashSet<Cart>();
            this.goodComment = new HashSet<goodComment>();
            this.goodReply = new HashSet<goodReply>();
            this.info = new HashSet<info>();
            this.infoComment = new HashSet<infoComment>();
            this.infoReply = new HashSet<infoReply>();
            this.MakePrivate = new HashSet<MakePrivate>();
            this.Order = new HashSet<Order>();
            this.Shop = new HashSet<Shop>();
        }

        /*public int user_id { get; set; }
        public string user_name { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string user_head { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public Nullable<byte> sex { get; set; }
        public string password { get; set; }
        public string user_introduce { get; set; }*/
        public int user_id { get; set; }
        [Required(ErrorMessage = "请输入用户名")]
        [RegularExpression(@"^[\\u4e00-\u9fa5_a-zA-Z0-9-\\w]{1,10}$", ErrorMessage = "限10个字符，支持中英文、数字、减号或下划线")]
        public string user_name { get; set; }
        [Required(ErrorMessage = "请输入手机号码")]
        [RegularExpression(@"^1[3|4|5|7|8][0-9]\d{8}$", ErrorMessage = "请输入有效的手机号码")]
        public string phone { get; set; }
        public string address { get; set; }
        public string user_head { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public Nullable<byte> sex { get; set; }
        [Required(ErrorMessage = "请输入密码")]
        [DataType(DataType.Password)]
        [RegularExpression(@"^([A-Z]|[a-z]|[0-9]|[`~!@#$%^&*()+=|{}':;',\\\\[\\\\].<>/?~！@#￥%……&*（）——+|{}【】‘；：”“’。，、？]){6,20}$", ErrorMessage = "密码必须为6-20 位的任意字母、数字、字符组合")]
        public string password { get; set; }
        [Required(ErrorMessage = "请确认密码")]
        [Compare("password", ErrorMessage = "与输入的密码不一致")]
        public string user_pwdAgain { get; set; }
        public string user_introduce { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<goodComment> goodComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<goodReply> goodReply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<info> info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoComment> infoComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoReply> infoReply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MakePrivate> MakePrivate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
